[package]
name = "svlog_cli"
version = "0.6.1"
authors = ["Pascal Huber <pascal.huber@resolved.ch>"]
edition = "2021"

[dependencies]
chrono = "0.4.26"
clap = { version = "4.1.13", features = ["derive", "env", "wrap_help"] }
svlog_util = { path = "../svlog_util" }