[package]
name = "svlog_cli"
version = "0.6.2"
authors = ["Pascal Huber <pascal.huber@resolved.ch>"]
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.3.23", features = ["derive", "env", "wrap_help"] }
svlog_util = { path = "../svlog_util" }
